ZigZagExchange/frontend

.env
.env.local
src/components/BridgeComponents/SwapButton/SwapButton.css
src/components/BridgeComponents/SwapButton/SwapButton.jsx
src/layout/Footer/Footer.jsx
src/layout/header/Header.jsx
src/pages/Bridge/index.jsx
src/pages/Bridge/style.css
src/routes/AppRoute.js

Could use some feedback and direction, thanks :)

feat: bridge UI

---

src/components/pages/TradePage/TradePage.jsx

Full book view

---

src/components/pages/ListPairPage/AllocationModal.jsx
src/components/pages/ListPairPage/ListPairPage.jsx
src/lib/api/API.js
src/lib/api/providers/APIZKProvider.js

- hardcode USDC as arweave allocation fee token & hardcode its decimal places (6)
- add baseFee and quoteFee hints showing notional value of the fee

purchase arweave bytes hot fix

---

src/components/atoms/Form/Submit.jsx
src/components/pages/ListPairPage/ListPairPage.jsx

- add reset button on perm listing

add reset button to base and quote fees

---

src/components/pages/ListPairPage/AllocationModal.jsx
src/components/pages/ListPairPage/ListPairPage.jsx
src/lib/api/providers/APIZKProvider.js

- fix USDC balance check in allocation modal

Fix USDC balance validation on AllocationModal

---

src/components/pages/TradePage/TradePage.jsx
src/lib/api/API.js

The site crashes right now if the websocket restarts or the network changes. 
These are quick fixes to remedy that.

Bug fix refreshing markets and refreshing websocket

---

src/components/pages/ListPairPage/ListPairForm.jsx
src/components/pages/ListPairPage/ListPairPage.jsx

- Form into its own component 
- welikethecleancode

Permissonless listing refactor

---

src/components/molecules/SpotForm/SpotForm.jsx

Hotfix SpotForm limit price input

---

public/index.html

add internal analytics and change title & meta description on new UI

add analytics and change title & meta description

---

src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx
src/lib/store/features/api/apiSlice.js

- display fees send from backend if available
- backend PR to add fee info to fills: https://github.com/ZigZagExchange/backend/pull/41#issue-1151812251

add fees over backend

---

src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx

fix/show fee as '--' while broadcasting

---

src/components/molecules/Chart/TradeChart/TradeChart.jsx
src/components/organisms/TradeDashboard/TradeDashboard.js
src/components/organisms/TradeDashboard/TradeSidebar/TradePriceBtcTable/TradePriceBtcTable.jsx
src/components/pages/BridgePage/BridgeCurrencySelector/BridgeCurrencySelector.jsx
src/lib/helpers/categories/index.js
src/lib/store/features/api/apiSlice.js

* Sets default TradingView Chart interval to 30 min
* Sorts pairs by volume
* Allows / to be used in search
* Adds FRAX + UST to stables list

Sort Listed Pairs By Volume

---

src/components/organisms/TradeDashboard/TradeSidebar/TradePriceBtcTable/TradePriceBtcTable.jsx

fix/uppercase for pairs like wstETH

---

src/components/organisms/TradeDashboard/TradeSidebar/TradePriceBtcTable/TradePriceBtcTable.jsx
src/lib/helpers/categories/index.js

Documented here: https://github.com/ZigZagExchange/frontend/issues/131 .
This should close it.

Update prices in sidebar with latest price

---

src/components/organisms/TradeDashboard/TradeSidebar/TradePriceBtcTable/TradePriceBtcTable.jsx
src/lib/store/features/api/apiSlice.js

Closes #144. 
Fixes switch from Rinkeby to mainnet and back.

Bug fixes for Bad market popup.

---

src/components/organisms/TradeDashboard/TradeBooks/TradeBooks.js
src/components/organisms/TradeDashboard/TradeDashboard.js
src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx
src/lib/api/API.js

merge after https://github.com/ZigZagExchange/backend/pull/116 is on prod

feat/backend sends fillWithoutFee now

---

src/components/pages/BridgePage/BridgeSwapInput/BridgeSwapInput.jsx

Fix max for numbers < 1 in Bridge

---

src/components/pages/BridgePage/Bridge/Bridge.jsx
src/components/pages/BridgePage/BridgeCurrencySelector/BridgeCurrencySelector.jsx
src/components/pages/BridgePage/BridgeSwapInput/BridgeSwapInput.jsx
src/lib/api/API.js

The Bridge's validation logic has been improved to use the exact
allowance value granted by the user. Previously only a value of
the MAX_ALLOWANCE constant was considered valid.
This allows users to minimize their risk.
https://user-images.githubusercontent.com/6083067/161906670-b26c35db-9d49-4d5e-a62d-4bc570ca8210.mov

Allow custom ERC20 allowance in Bridge

---

src/components/atoms/InputField/InputField.demo.jsx
src/components/atoms/InputField/InputField.jsx
src/components/atoms/InputField/index.js
src/components/pages/DSLPage/DSLPage.jsx

- Built the base component for the Input field
- Updated the styles based on the Figma redesign
- Added options and styles for Labeled Input Field Component
- Added options and styles for Search Input Field Component
- Added the demo for the Input Field Component
- `src/components/atoms/InputField/index.js`
- `src/components/atoms/InputField/InputField.jsx`
- `src/components/atoms/InputField/InputField.demo.jsx`
- `src/components/pages/DSLPage/DSLPage.jsx`
https://user-images.githubusercontent.com/54931597/162503119-e6549285-d25c-46fc-be83-96684b61fe51.mp4

Reskin - Input Field Component

---

src/lib/api/providers/APIZKProvider/APIZKProvider.js

change rinkeby url

---

src/components/atoms/CheckBox/CheckBox.demo.jsx
src/components/atoms/CheckBox/CheckBox.jsx
src/components/atoms/CheckBox/index.js
src/components/pages/DSLPage/DSLPage.jsx

- Built the base component for the CheckBox component
- Updated the styles based on the Figma redesign
- Added options and styles for Labeled CheckBox Component
- Added options for left-side and right-side CheckBox
- Added the demo for the CheckBox Component
- `src/components/atoms/CheckBox/index.js`
- `src/components/atoms/CheckBox/CheckBox.jsx`
- `src/components/atoms/CheckBox/CheckBox.demo.jsx`
- `src/components/pages/DSLPage/DSLPage.jsx`
https://user-images.githubusercontent.com/54931597/162607685-92325831-3c54-405c-bd54-e86c1e737726.mp4

Reskin - Checkbox Component

---

src/components/atoms/Text/Text.jsx
src/components/molecules/Button/Button.jsx
src/components/molecules/Dropdown/AccountDropdown.jsx
src/components/molecules/Dropdown/Dropdown.demo.jsx
src/components/molecules/Dropdown/Dropdown.jsx
src/components/molecules/Dropdown/index.js
src/components/molecules/ExpandableButton/AccountButton.jsx
src/components/molecules/ExpandableButton/ExpandableButton.jsx
src/components/molecules/ExpandableButton/index.js
src/components/molecules/IconButton/IconButton.jsx
src/components/molecules/IconButton/index.js
src/components/molecules/TabMenu/StyledTab.jsx
src/components/molecules/TabMenu/Tab.jsx
src/components/molecules/TabMenu/TabMenu.demo.jsx
src/components/molecules/TabMenu/TabMenu.jsx
src/components/molecules/TabMenu/index.js
src/components/pages/DSLPage/DSLPage.jsx
src/lib/theme/typography.js

- Built the Expandable Button component
- Built the Account Button component
- Built the Dropdown component
- Built the Account Dropdown component
- Built the TabMenu & Tab components
- Updated some styles
- Added new Font styles
- `src/components/molecules/ExpandableButton/index.js`
- `src/components/molecules/ExpandableButton/ExpandableButton.jsx`
- `src/components/molecules/ExpandableButton/AccountButton.jsx`
- `src/components/molecules/IconButton/index.js`
- `src/components/molecules/IconButton/IconButton.js`
- `src/components/molecules/Dropdown/index.js`
- `src/components/molecules/Dropdown/Dropdown.jsx`
- `src/components/molecules/Dropdown/Dropdown.demo.jsx`
- `src/components/molecules/Dropdown/AccountDropdown.jsx`
- `src/components/molecules/TabMenu/index.js`
- …

Reskin - Various Components

---

src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx

Fix of Issue #230

---

src/components/pages/BridgePage/BridgeSwapInput/BridgeSwapInput.jsx
src/components/pages/BridgePage/NewBridgeModal/NewBridgeModal.jsx
src/lib/theme/colors.js

- Updated the background color of dropdown components
- Updated the styles of a hyperlink element

Reskin - Some Updates

---

src/components/molecules/SpotForm/SpotForm.jsx
src/components/organisms/TradeDashboard/TradeSidebar/TradeSidebar.js
src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx
src/lib/store/features/api/apiSlice.js

#476 and #513

---

src/components/organisms/TradeDashboard/TradeBooks/OrdersBook.js
src/components/organisms/TradeDashboard/TradeBooks/TradePriceTable/TradePriceTable.jsx
src/components/organisms/TradeDashboard/TradeDashboard.js

#708 #696 #688

---

src/components/organisms/TradeDashboard/TradeBooks/TradePriceTable/TradePriceTable.css
src/components/organisms/TradeDashboard/TradeBooks/TradePriceTable/TradePriceTable.jsx
src/components/organisms/TradeDashboard/TradeBooks/TradeRecentTable/TradeRecentTable.css
src/components/organisms/TradeDashboard/TradeBooks/TradeRecentTable/TradeRecentTable.jsx
src/components/organisms/TradeDashboard/TradeSidebar/TradeSidebar.js

issue #694: fix firefox scrollbars on trade page

---

src/components/organisms/TokenDropdownModal/TokenDropDownModal.jsx
src/components/pages/SwapPage/SwapContainer/SwapContianer.js
src/components/pages/SwapPage/SwapPage.jsx
src/components/pages/SwapPage/TransationSettings/TransactionSettings.jsx

Fix/issue: #693

---

src/components/molecules/SpotForm/SpotForm.jsx

Fix wrong msg for quote size, and quote price

fix order msg

---

src/components/organisms/TokenDropdownModal/TokenDropDownModal.jsx
src/components/pages/BridgePage/BridgeContainer/BridgeContainer.jsx
src/components/pages/BridgePage/BridgeContainer/SwitchNetwork/NetworkDropdown.js
src/components/pages/BridgePage/BridgeContainer/SwitchNetwork/SwitchNetwork.jsx
src/components/pages/BridgePage/BridgeContainer/TransactionSettings/TransactionSettings.jsx
src/components/pages/BridgePage/BridgePage.jsx
src/components/pages/BridgePage/TransferHistory/TransferHistory.jsx

fix: fixed issue-#752-#768-#769

---

src/components/molecules/Dropdown/Dropdown.jsx
src/components/organisms/Header/Header.jsx

fix: added menu icons and contact

---

src/components/molecules/Dropdown/AccountDropdown.jsx
src/components/molecules/Dropdown/Dropdown.jsx
src/components/molecules/SpotForm/SpotForm.jsx
src/components/organisms/TradeDashboard/TradeSidebar/SpotBox/SpotBox.jsx
src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx
src/components/pages/ConvertPage/ConvertContianer/ConvertContianer.js
src/components/pages/ConvertPage/ConvertPage.jsx
src/components/pages/ConvertPage/TransationSettings/TransactionSettings.jsx
src/lib/api/API.js
src/lib/api/providers/APIArbitrumProvider.js
src/lib/api/providers/APIZKProvider/APIZKProvider.js

Convert:
- adding slippage https://github.com/ZigZagExchange/frontend/pull/874
- fixing error msgs
- update pending order msg
- fixing the ladder price logic -> less open orders
- adding arbitrum (EVM chain) ladder price logic 
- adding allowance for aribtrum (and other EVM chains)
- adding an allowance flow to let the user approve the exchange contract
SpotBox:
- small spotBox arbitrum fixes
OrderTable:
- remove logs
API:
- move common function to API.js
- increse precision

rework multiple convert features - update api

---

src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx
src/lib/api/API.js

fix: updated filled value in orders table

---

package.json
src/components/organisms/Header/Header.jsx
yarn.lock

fix: updated header responsive

---

src/components/organisms/TradeDashboard/TradeMarketSelector/TradeRatesCard/SettingsModal.jsx
src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx

fix: re-updated cancel all button settings

---

src/components/organisms/TradeDashboard/TradeSidebar/TradeSidebar.js

fix: updated scrollbar width in sidebar

---

src/components/organisms/TradeDashboard/TradeSidebar/TradeSidebar.js

fix: updated sportform height

---

src/App.css
src/components/organisms/TradeDashboard/TradeTables/OrdersTable/FillCard/FillCard.jsx

fix: updated mobile screen of trade card

---

src/components/hooks/useCoinEstimator.js
src/components/organisms/TradeDashboard/TradeMarketSelector/TradeMarketSelector.js
src/components/pages/ConvertPage/ConvertPage.jsx
src/lib/api/API.js
src/lib/api/providers/APIArbitrumProvider.js
src/lib/api/providers/APIZKProvider/APIZKProvider.js
src/lib/store/features/api/apiSlice.js
src/lib/store/index.js

Fix markets and currencies dropdown so they change when the chain changes

---

src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx

fix: updated loading spinner in order status

---

src/components/hooks/useCoinEstimator.js
src/components/organisms/TradeDashboard/TradeTables/OrdersTable/OrdersTable.jsx

fix: displayed icETH balances in wallet

---

src/components/hooks/useCoinEstimator.js
src/components/molecules/Dropdown/AccountDropdown.jsx

Reverts ZigZagExchange/frontend#937

Revert "fix: displayed icETH balances in wallet"

---

src/components/hooks/useCoinEstimator.js
src/components/pages/ConvertPage/ConvertPage.jsx

fix: fixed convert clash error

---

src/AppRoutes.js
src/components/pages/NotFoundPage/NotFoundPage.jsx

fix: made NotFoundPage

---

src/components/molecules/SpotForm/SpotForm.jsx

fix: fixed highslippage logic

---

src/components/pages/BridgePage/BridgeContainer/BridgeContainer.jsx
src/components/pages/BridgePage/BridgeContainer/SlippageWarningModal/SlippageWarningModal.jsx

fix: fixed confirm text center

---

src/lib/utils.js

fix: fixed NaN value for the total wallet balance

---

src/App.css
src/components/organisms/TradeDashboard/TradeTables/OrdersTable/FillCard/FillCard.jsx
src/lib/api/providers/APIZKProvider/APIZKProvider.js
src/lib/store/features/api/apiSlice.js

fix: updated low balance warning toast

---

src/components/molecules/SpotForm/SpotForm.jsx

fix: reset amounts when order type and side is changed

---

src/App.css

fix: updated close button scroll in wallet modal

---

src/components/organisms/TokenDropdownModal/TokenDropDownModal.jsx
src/components/pages/BridgePage/BridgePage.jsx

fix: disabled guide popup in bridge

---

src/components/organisms/TokenDropdownModal/TokenDropDownModal.jsx
src/components/pages/BridgePage/BridgeContainer/BridgeContainer.jsx
src/components/pages/BridgePage/BridgeContainer/SelectAsset/SelectAsset.jsx

fix: updated token selection in token dropdown modal

---

src/components/pages/BridgePage/BridgeContainer/BridgeContainer.jsx
src/components/pages/BridgePage/BridgeContainer/SelectAsset/SelectAsset.jsx

fix: fixed lower balance format

---

src/components/pages/BridgePage/BridgeContainer/BridgeContainer.jsx
src/components/pages/BridgePage/TransferHistory/TransferHistory.jsx
src/lib/api/API.js
src/lib/api/providers/APIZKProvider/APIZKProvider.js
src/lib/store/features/api/apiSlice.js
src/lib/store/index.js

fix: fixed zksync-ethereum notification in bridge

---

src/components/organisms/Header/Header.jsx
src/components/organisms/TradeDashboard/NewFeaturesPopup.jsx
src/lib/api/providers/APIZKProvider/APIZKProvider.js

fix: added language dropdown in mobile sidemenu

---

package.json
src/components/molecules/Button/ConnectWalletButton.jsx
src/lib/api/API.js
yarn.lock

fix: added coinbase wallet option

---

src/lib/api/providers/APIZKProvider/APIZKProvider.js

Reverts ZigZagExchange/frontend#1133

Revert "simplify wallet creation"

---

src/components/pages/BridgePage/BridgeContainer/BridgeContainer.jsx
src/components/pages/BridgePage/BridgeContainer/constants.js
src/components/pages/BridgePage/BridgePage.jsx
src/lib/api/API.js

It doesn't make us money and costs us time to maintain. 
This replaces it with a link to the Zksync canonical bridge.

Get rid of ETH -> zksync deposit bridge

---

src/components/atoms/ZapBanner/ZapBanner.css
src/components/atoms/ZapBanner/ZapBanner.jsx
src/components/atoms/ZapBanner/index.js
src/components/pages/BridgePage/BridgePage.jsx

add zap banner to bridge page
